### PR TITLE
Migrate to autocomplete-plus v2.0 providers API

### PR DESCRIPTION
**Pull request by alkama**
* Use the 2.0.0 Provider API from "autocomplete-plus"
* Add new setting to blacklist user-specified selectors from triggering completion
* Benefit from the new GUI possibilities of v2 provider's API to give clues about the types of the proposed completions
* Update dependencies

### CODE REVIEW

**Comment by edubkendo** [comment]
Is this one ready for merge? Looks really nice.

**Comment by alkama** [comment]
Hello :) Yup it should be good to go as a 0.11.0 !
Wish I knew how you did your gif capture, it looks pretty cool now :)

**Comment by edubkendo** [comment]
I use http://www.cockos.com/licecap/, then create a tagged release and upload the image there to get a good link to it. I can help with that part if you take the screenshots. I don't have rust installed currently.

**Comment by edubkendo** [comment]
Ok should be all published!

**Comment by alkama** [comment]
Awesome :) Thanks for your kind help as usual !

**Comment by hastebrot** [comment]
Great PR! Tested it under Windows and it works perfect.

I wonder if parameter previews are in scope of autocomplete-plus and racer, besided auto-completion.

**Pull request merged**
