### PR TITLE
Use the new Provider API from "autocomplete-plus"

### PR DESCRIPTION
**Pull request by alkama**
- Conform to the new autocomplete-plus Providers API
- Back to calling the "racer" process asynchronously (along with temporary file creation)
- Code cleanup and safety

### CODE REVIEW

**Comment by edubkendo** [comment]
Very nice work! Go ahead and merge this when you are happy with it and I'll pull it down and cut a release.

**Comment by edubkendo** [comment]
If you don't mind, I think I will borrow a lot of this for atom-rsense which I really need to do something with, it's in a pretty borked state right now.

**Comment by alkama** [comment]
Oh I dont mind at all ! Go ahead :)
And it seems to work fine here, so I guess you can merge whenever you want.

**Comment by edubkendo** [comment]
awesome, just published the new package.

**Pull request merged**
