### PR TITLE
Avoid misconfiguration and try to help racer to find a Cargo.toml

### PR DESCRIPTION
**Pull request by alkama**
* Rewrite the README file so that it warns for misconfiguration and is more structured.
* Do not launch completion if the configuration is obviously wrong.
* Check that "racer.racerBinPath" points to a valid file.
* Check that "racer.rustSrcPath" points to a valid directory.
* Rescan the current project path for each completion because it can change during the editor's life.
* Write the temporary file directly in the project path to help racer locate a related Cargo.toml.
* Clean temp files immediately after racer returns.

### CODE REVIEW

**Comment by alkama** [comment]
If it didn't mess it, it should be valid for a v0.12 and should fix #26

**Comment by edubkendo** [comment]
I don't understand what you mean by, if it didn't mess it?

**Comment by alkama** [comment]
I just meant that it should work fine! (but that's unless I missed a corner case, we're human after all)

**Comment by edubkendo** [comment]
:)

**Comment by edubkendo** [comment]
Sorry, messed up the publishing and skipped a minor version but it's published.

**Comment by alkama** [comment]
Cool! Thanks!

What remains now is to be more vocal about misconfigurations.
For now the errors go to the console and it seems Atom doesnt warn anymore about errors in the console. I'll see if I can use a message panel instead.

Maybe later I'll see if I can port a "go to definition" and/or snippet feature from racer.

**Comment by mcanders** [comment]
Unfortunately these changes did not fix completion from external crates using Cargo.toml or completion from files within the project.  Are these completions working for you now?  The only completions I get are from the current file and rust/src.  What configurations do you have?  I am running Linux 4.0.5, gnome-shell 3.16, Atom .207, rust nightly (as of today), and current racer.

**Comment by alkama** [comment]
Hum, I'm on OSX. Can you check if racer is working correctly in isolation?
It should be fairly easy to mimic the atom-racer using a commandline and see if racer responds correctly.

something like:
`RUST_SRC_PATH=[RUST_SRC]:[ATOM_PROJECT_ROOT] [PATH_TO_RACER]/racer complete [NUM_ROW] [NUM_COL] [ATOM_PROJECT_ROOT]/[CURRENT_INCOMPLETE_FILE]`

Because that's basically what we are submitting and just using the results.

If it doesn't work, it's probably something to issue and debug at racer instead :)

**Comment by mcanders** [comment]
I get cargo and project file completions when I run racer manually using the format you outlined.  Now that I know what works, I will experiment with atom-racer and see if I can get something working.

**Comment by alkama** [comment]
Excellent :)
Hope you'll spot what's wrong.

**Pull request merged**
