### PR TITLE
Fixes Atom API deprecated use of project.getPath()

### LINKED ISSUE #21: Project.getPath is deprecated.
Use ::getPaths instead
```
Project.getPath (C:\Users\Jerom\AppData\Local\atom\app-0.190.0\resources\app\src\project.js:585:12)
RacerClient.process_env_vars (C:\Users\Jerom\.atom\packages\racer\lib\racer-client.coffee:48:50)
```

### PR DESCRIPTION
**Pull request by alkama**
Use getPath()[0] instead.

Fixes #21

### CODE REVIEW

**Comment by alkama** [comment]
This can be pushed as 0.10.1 :)

**Comment by edubkendo** [comment]
done :)

**Comment by alkama** [comment]
awesome :+1:

**Comment by JeromSar** [comment]
@alkama Blazingly fast! :)

**Pull request merged**
