### PR TITLE
Add autocomplete-plus snippets for functions

### PR DESCRIPTION
**Pull request by kylewlacy**
Snippets!

### CODE REVIEW

**Comment by edubkendo** [comment]
@alkama have you seen this one yet?

**Comment by Furyhunter** [comment]
Could you add a configuration option to put it in the description field instead of the name? So that it doesn't resize the dialog so much.

**Comment by kylewlacy** [comment]
@Furyhunter From what I understand, the autocomplete dialog shouldn't be resizing (an overflowing name should be truncated with '...'). See the screenshots from [this PR in the `autocomplete-plus` repo](https://github.com/atom/autocomplete-plus/pull/334) for what a completion *should* look like.

That said, I'm also not the repo owner, so it's ultimately not my say. However, using the description to show the full name and type info would conflict with using the description to show a function's docstring (which is what the autocomplete-plus wiki recommends, and is something I'd like to see in a future version of the racer plugin).

**Comment by Furyhunter** [comment]
I suppose if there's not another recommended way of doing it, then showing the function declaration is the best way. Maybe when racer gets type inferencing support, the same can be done for variable bindings, statics and consts.

**Comment by edubkendo** [comment]
@kylewlacy this looks really good. I kind of like seeing the function signatures, but I don't know how annoying the window resizing stuff is...

**Comment by cburgdorf** [comment]
I'd vote for merging this as is :+1:

**Comment by edubkendo** [comment]
Yeah, I'll merge and if there are any problems someone can address them in another PR.

**Comment by edubkendo** [comment]
Merged and published. Thanks for all your work guys!

**Comment by cburgdorf** [comment]
:+1:

**Comment by armink** [comment]
:+1:

**Pull request merged**
