### PR TITLE
Fixes broken suggestions, update manual, contributors and changelog.

### LINKED ISSUE #38: Can't get this working
Hi, think I have everything set up correctly, but I can't get anything to autocomplete.

Racer works fine from the CLI, I've set the paths up in the config, and I have language-rust installed. Not sure where I'm going wrong.

Config:
```
  racer:
    racerBinPath: "/usr/bin/racer"
    rustSrcPath: "/usr/src/rust/src/"
```

Some racer output:
```
/usr/bin/racer complete std::io::Br
MATCH Broadcast,628,11,/usr/src/rust/src/libstd/io/mod.rs,Struct,pub struct Broadcast<T, U> {
MATCH Broadcast,628,11,./libstd/io/mod.rs,Struct,pub struct Broadcast<T, U> {
```

Source dir;
```
ls -l
total 232
-rw-r--r-- 1 tom tom 37519 May 13 21:03 AUTHORS.txt
-rwxr--r-- 1 tom tom 40449 May 13 21:03 configure*
-rw-r--r-- 1 tom tom  6100 May 13 21:03 CONTRIBUTING.md
-rw-r--r-- 1 tom tom 16809 May 13 21:03 COPYRIGHT
-rw-r--r-- 1 tom tom 10847 May 13 21:03 LICENSE-APACHE
-rw-r--r-- 1 tom tom  1071 May 13 21:03 LICENSE-MIT
-rw-r--r-- 1 tom tom 10059 May 13 21:03 Makefile.in
drwxr-xr-x 1 tom tom    32 May 13 21:03 man/
drwxr-xr-x 1 tom tom   380 May 14 07:25 mk/
-rw-r--r-- 1 tom tom  4355 May 13 21:03 README.md
-rw-r--r-- 1 tom tom 86070 May 13 21:03 RELEASES.md
drwxr-xr-x 1 tom tom   920 May 14 07:25 src/
```

### PR DESCRIPTION
**Pull request by alkama**
Fixes #38

### CODE REVIEW

**Comment by alkama** [comment]
@edubkendo This should be good for a v0.15.1 !

**Comment by edubkendo** [comment]
Thanks for all your work on this plugin @alkama . I'll get back to rust eventually and it is really nice to know that such a great plugin will be waiting for me.

**Comment by alkama** [comment]
Hehe:) thanks for creating the plugin ! I didn't do much, really.

**Comment by alkama** [comment]
Shame on me. I made a horrible typo in the readme... > "opened"...
How terribly ugly.
Will fix with next update.

**Pull request merged**
